---
apiVersion: batch/v1
kind: Job
metadata:
  name: liveness-check
spec:
  backoffLimit: 0
  completions: 1
  parallelism: 1
  template:
    spec:
      automountServiceAccountToken: true
      containers:
        - args:
            - echo
            - all good
          image: busybox:1
          name: busybox
      initContainers:
        - env:
            - name: NAMESPACE
              value: default
            - name: LABEL_SELECTORS
              value: app.kubernetes.io/name=nginx
            - name: ENDPOINT
              value: /
          image: ghcr.io/meysam81/liveness-check
          name: liveness-check
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsGroup: 65534
            runAsNonRoot: true
            runAsUser: 65534
      restartPolicy: OnFailure
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
        supplementalGroups: []
        sysctls: []
      serviceAccountName: liveness-check
